---
title: "R Notebook"
output: html_notebook
---

``` {r}
library(tidyverse)
library(PtProcess)
library(stelfi)
library(ACDm)
```

``` {r}
df = read.csv('counting_trades_clean.csv')
Tmax = 25200
breaks <- seq(0, Tmax, by = 1)
counts <- hist(df$t, breaks = breaks, plot = FALSE)$counts
```

Basic Hawkes:
``` {r}
t_u = unique(df$t)

params = list(0.01, 1, 1)
hawkes_m = fit_hawkes(times = unique(t_u),
                      parameters = params,
                      model = 1)

estim_params = get_coefs(hawkes_m)[,1]

hawkes_p = show_hawkes(hawkes_m, type = 'fitted')
hawkes_p = hawkes_p + 
  labs(x = 'Time (s)', title = 'Estimated Intensity of Hawkes Model') #+
  geom_col(data = data.frame(t = 1:Tmax, counts = counts), aes(x = t, y = counts), fill = "steelblue2", alpha = 0.6, width = 1) +
  ylim(0, 10)
hawkes_p
``` 

Fixed intensity bootstrap:
``` {r}
B = 1000
boot_params = data.frame(mu = numeric(B), 
                         alpha = numeric(B), 
                         beta = numeric(B))
for (i in 1:B) {
  t_b = sim_hawkes(mu = estim_params[1],
                   alpha = estim_params[2],
                   beta = estim_params[3],
                   n = Tmax,
                   seed = 16)
  m_b = fit_hawkes(times = t_b,
                   parameters = estim_params,
                   model = 1)
  params_b = get_coefs(m_b)[,1]
  for (j in 1:3) {
      boot_params[i,j] = params_b[j] |> unname()
  }
}

boot_params = boot_params[1:572,] |> unname()
```

Rescaling Hawkes Wait Times:
``` {r}
lambda_hawkes <- function(t, params, arrivals) {
  mu = unname(params[1])
  alpha = unname(params[2])
  beta = unname(params[3])
  
  sapply(t, function(ti) {
    if (ti == 0) return(mu)
    
    H = arrivals[arrivals < ti]
    if (length(H) == 0) return(mu)
    
    excitation = sum(exp(-beta * (ti - H)))
    return(mu + alpha * excitation)
  })
}

rescale_hawkes_times <- function(arrivals, params) {
  z = numeric(length(arrivals))
  
  for (i in seq_along(arrivals)) {
    t0 = if (i == 1) 0 else arrivals[i - 1]
    t1 = arrivals[i]
    
    z[i] = integrate(lambda_hawkes, lower = t0, upper = t1, params = params, arrivals = arrivals)$value
  }
  
  return(z)
}

z_hawkes = rescale_hawkes_times(arrivals = t_u, params = estim_params)
```

Hawkes Diagnostics:
``` {r}
ggplot(data.frame(z = z_hawkes), aes(sample = z)) +
  stat_qq(distribution = qexp, dparams = list(rate = 1), size = 2) +
  stat_qq_line(distribution = qexp, dparams = list(rate = 1), linetype = "dashed", color = "blue") +
  labs(title = "Exponential Q-Q Plot",
       x = "Theoretical Quantiles (Exp(1))",
       y = "Empirical Quantiles")

acf(z_hawkes)

t_rescaled = cumsum(z_hawkes)
z_Tmax = round(max(t_rescaled)) + 1

counts_rescaled = hist(t_rescaled, breaks = seq(0, z_Tmax, by=1), plot=F)$counts
ff_hawkes = var(counts_rescaled) / mean(counts_rescaled)

gcrit_l = qgamma(0.025, (length(counts_rescaled)-1)/2, scale=2/(length(counts_rescaled)-1), lower.tail = T)
gcrit_u = qgamma(0.025, (length(counts_rescaled)-1)/2, scale=2/(length(counts_rescaled)-1), lower.tail = F)

gcrit_l
gcrit_u
ff_hawkes
```

ACD Fitting:
``` {r}
x_u = df$x[which(df$x != 0)]
eacd_fit = acdFit(durations = x_u,
                  dist = 'exponential', 
                  order = c(1, 1), 
                  startPara = c(0.1, 0, 0)) 

ggplot(data.frame(sample = eacd_fit$residuals), aes(sample = sample)) +
  stat_qq(distribution = qexp, dparams = list(rate = 1), size = 2) +
  stat_qq_line(distribution = qexp, dparams = list(rate = 1), linetype = "dashed", color = "blue") +
  labs(title = "Exponential Q-Q Plot",
       x = "Theoretical Quantiles (Exp(1))",
       y = "Empirical Quantiles")

acf(eacd_fit$residuals)

plotScatterAcd(eacd_fit, x = "muHats", y = "residuals")
plotHazard(eacd_fit)
```

- Explore process 
  -visualizations
  -generate new processes using params (what else could have happened)
  -
  
  -1.767932e+04
AIC            3.536864e+04
BIC            3.541198e+04
MSE            4.132845e-01

-1.767908e+04
AIC            3.536417e+04
BIC            3.539017e+04
MSE            4.132665e-01
